apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fj5h
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-fj5h@sha256:eaf9fbc3398f8839dc8ce38623d4a9c3d4e08ca185a985cbebddfe120af95968
        name: my-nodejs
        resources: {}
status: {}
